#!/bin/sh
#
# firewall: http://www.zip.com.au/~raf2/lib/software/firewall
#
# Copyright (C) 1999, 2000 raf <raf2@zip.com.au>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# or visit http://www.gnu.org/copyleft/gpl.html
#

# firewall - Startup script for an ipchains packet filtering firewall
#
# name: /etc/rc.d/init.d/firewall
# description: firewall provides network security
# lockfile: /var/lock/subsys/firewall
# programs: /usr/local/sbin/{fwup,fwdown}
# config: /etc/firewall.policy
#
# 20000601 raf <raf2@zip.com.au>

# Source networking configuration (if redhat)

[ -r /etc/sysconfig/network ] && . /etc/sysconfig/network

# Check that networking is required (if redhat)

[ "$NETWORKING" = "no" ] && exit 0

# Locations of the files we will need

lock=/var/lock/subsys/firewall
policy=/etc/firewall.policy
fwup=/usr/local/sbin/fwup
fwdown=/usr/local/sbin/fwdown
ipchains=/sbin/ipchains
ipmasqadm=/usr/sbin/ipmasqadm
ip=/sbin/ip

die()
{
	logger -t "`basename $0`" -p daemon.notice -s $*
	exit 1
}

# See how we were called
case "$1" in

	start|up)
		[ -e $lock ] && die "The Firewall is already up"

		[ ! -x $fwup ] && die "Failed to find executable $fwup"
		[ ! -r $policy ] && die "Failed to find readable $policy"

		policy="$policy" $fwup && touch $lock
		;;

	stop|down)
		[ ! -e $lock ] && die "The Firewall is already down"

		[ ! -x $fwdown ] && die "Failed to find executable $fwdown"
		[ ! -r $policy ] && die "Failed to find readable $policy"

		policy="$policy" $fwdown && rm -f $lock
		;;

	status)
		[ -e $lock ] && echo "The Firewall is up" || echo "The Firewall is down"
		;;

	probe)
		[ ! -x $ipchains ] && die "failed to find executable $ipchains"

		echo ipchains -L -v -n
		echo ~~~~~~~~~~~~~~~~~
		$ipchains -L -v -n

		echo
		echo ipchains -M -L -v -n
		echo ~~~~~~~~~~~~~~~~~~~~
		$ipchains -M -L -v -n

		if [ -x $ipmasqadm ]
		then
			echo
			echo ipmasqadm portfw -l -n
			echo ~~~~~~~~~~~~~~~~~~~~~~
			$ipmasqadm portfw -l -n
		fi

		if [ -x $ip ]
		then
			echo
			echo ip rule show
			echo ~~~~~~~~~~~~
			$ip rule show
			echo
			echo ip route show
			echo ~~~~~~~~~~~~~
			$ip route show
		fi
		;;

	restart)
		$0 stop
		$0 start
		;;

	reload)
		rm -f $lock
		$0 start
		;;

	*)
		echo "usage: $0 {start|stop|up|down|restart|reload|status|probe}"
		exit 1
		;;

esac

exit 0

# vi:set ts=4 sw=4:
