#!/bin/sh
#
# firewall - http://fwup.org/
#
# Copyright (C) 1999-2001 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# or visit http://www.gnu.org/copyleft/gpl.html
#

# firewall - control script for an ipchains packet filtering firewall
#
# chkconfig: 2345 09 91
# description: Firewall provides network security and address/port translation
# lockfile: /var/lock/subsys/firewall
# config: /etc/firewall.policy
#
# 20010815 raf <raf@raf.org>

# Set the path explicitly

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin
export PATH

# Source networking configuration (if redhat)

[ -r /etc/sysconfig/network ] && . /etc/sysconfig/network

# Check that networking is required (if redhat)

[ "$NETWORKING" = "no" ] && exit 0

# Locations of the files we will need

locate()
{
	for dir in `echo $PATH | sed 's/:/ /g'`
	do
		[ -x "$dir/$1" ] && echo "$dir/$1" && break
	done
}

lock="/var/lock/subsys/firewall"
policy="/etc/firewall.policy"
fwup="`locate fwup`"
fwdown="`locate fwdown`"
ipchains="`locate ipchains`"
ipmasqadm="`locate ipmasqadm`"
ip="`locate ip`"

die()
{
	logger -t "`basename $0`" -p daemon.notice -s $*
	exit 1
}

# See how we were called
case "$1" in

	start|up)
		[ -e "$lock" ] && die "The Firewall is already up"
		[ -z "$fwup" ] && die "Failed to find executable fwup"
		[ ! -r "$policy" ] && die "Failed to find readable $policy"
		policy="$policy" "$fwup" && touch "$lock"
		;;

	stop|down)
		[ ! -e "$lock" ] && die "The Firewall is already down"
		[ -z "$fwdown" ] && die "Failed to find executable fwdown"
		[ ! -r $policy ] && die "Failed to find readable $policy"
		policy="$policy" "$fwdown" && rm -f "$lock"
		;;

	status)
		[ -e "$lock" ] && echo "The Firewall is up" || echo "The Firewall is down"
		;;

	probe)
		[ -z "$ipchains" ] && die "Failed to find executable ipchains"

		echo ipchains -L -v -n
		echo ~~~~~~~~~~~~~~~~~
		"$ipchains" -L -v -n

		echo
		echo ipchains -M -L -v -n
		echo ~~~~~~~~~~~~~~~~~~~~
		"$ipchains" -M -L -v -n

		if [ -n "$ipmasqadm" ]
		then
			echo
			echo ipmasqadm portfw -l -n
			echo ~~~~~~~~~~~~~~~~~~~~~~
			"$ipmasqadm" portfw -l -n
			echo
			echo ipmasqadm mfw -L -n
			echo ~~~~~~~~~~~~~~~~~~~
			"$ipmasqadm" mfw -L -n
		fi

		if [ -n "$ip" ]
		then
			echo
			echo ip rule show
			echo ~~~~~~~~~~~~
			"$ip" rule show
			echo
			echo ip route show
			echo ~~~~~~~~~~~~~
			"$ip" route show
		fi
		;;

	restart)
		$0 stop
		$0 start
		;;

	reload)
		rm -f "$lock"
		$0 start
		;;

	*)
		echo "usage: $0 {start|stop|up|down|restart|reload|status|probe}"
		exit 1
		;;

esac

exit 0

# vi:set ts=4 sw=4:
