#!/bin/sh
#
# firewall - http://fwup.org/
#
# Copyright (C) 1999-2004 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# or visit http://www.gnu.org/copyleft/gpl.html
#

# make-uninstall - Uninstall the firewall scripts and policy (without make)
#
# 20041215 raf <raf@raf.org>

. ./firewall.policy
unmodify() { if [ -x $1 ]; then grep -v '/firewall reload' $1 > /tmp/fwun.$$; cat /tmp/fwun.$$ > $1; rm -f /tmp/fwun.$$; fi; }
rm -f /etc/rc.d/init.d/firewall /etc/init.d/firewall /etc/firewall /usr/local/sbin/fwup /usr/local/sbin/fwdown /etc/firewall.policy /etc/rc.d/rc?.d/[SK][0-9][0-9]firewall /etc/rc?.d/[SK][0-9][0-9]firewall /etc/ppp/ip-up.d/00firewall /etc/ppp/ip-down.d/00firewall
for modified in /etc/rc.d/rc.local /etc/rc.local /etc/ppp/ip-up.local /etc/ppp/ip-down.local /etc/dhcpc/dhcpcd-*.exe /etc/dhclient-exit-hooks /etc/pump.firewall; do unmodify $modified; done
