#!/bin/sh
#
# firewall - http://fwup.org/
#
# Copyright (C) 1999-2001 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# or visit http://www.gnu.org/copyleft/gpl.html
#

# make-meta-install - Install the meta-firewall control script (without make)
#
# 20010815 raf <raf@raf.org>

die() { echo "$0: $*" >&2; exit 1; }

mfwd="/etc/meta-firewall.d"
[ -d "$mfwd" ] || mkdir "$mfwd" || die "failed to create $mfwd"
install -m 744 make-install "$mfwd" || die "failed to install make-install into $mfwd"
install -m 744 make-uninstall "$mfwd" || die "failed to install make-uninstall into $mfwd"
install -m 744 make-policy "$mfwd" || die "failed to install make-policy into $mfwd"
install -m 744 make-ls "$mfwd" || die "failed to install make-ls into $mfwd"
install -m 744 firewall "$mfwd" || die "failed to install firewall into $mfwd"
install -m 744 fwup "$mfwd" || die "failed to install fwup into $mfwd"
install -m 744 fwdown "$mfwd" || die "failed to install fwdown into $mfwd"
install -m 644 firewall.policy "$mfwd" || die "failed to install firewall.policy into $mfwd"
if [ -d /etc/rc.d/init.d ]; then install -m 744 meta-firewall /etc/rc.d/init.d || die "failed to install meta-firewall into /etc/rc.d/init.d"
elif [ -d /etc/init.d ]; then install -m 744 meta-firewall /etc/init.d || die "failed to install meta-firewall into /etc/rc.d"
elif [ -x /etc/rc.d/rc.local ]; then install -m 744 meta-firewall /etc || die "failed to install meta-firewall into /etc"
elif [ -x /etc/rc.local ]; then install -m 744 meta-firewall /etc || die "failed to install meta-firewall into /etc"
else exit 1
fi
