#!/bin/sh
#
# firewall - http://fwup.org/
#
# Copyright (C) 1999-2004 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# or visit http://www.gnu.org/copyleft/gpl.html
#

# make-lrp - Generate an LRP package (without make)
#
# 20041231 raf <raf@raf.org>

# Prepare an LRP style tree in which to install the firewall

root="lrp"
export root

rm -rf "$root"
mkdir "$root"

mkdir -p "$root/usr/local/sbin"
mkdir -p "$root/etc/init.d"

for rc in 0 1 2 3 4 5 6 S
do
	mkdir "$root/etc/rc$rc.d"
done

touch "$root/etc/dhclient.conf" # in case the dhclient package is installed
mkdir "$root/etc/ppp"           # in case the ppp package is installed
mkdir "$root/etc/ppp/ip-up.d"
mkdir "$root/etc/ppp/ip-down.d"

# Install the firewall into $root

START_LEVELS="2 3 4 5"
STOP_LEVELS="0 1 6 S"
START_TIME="00"
STOP_TIME="99"
export START_LEVELS STOP_LEVELS START_TIME STOP_TIME

PATH="`echo $0 | sed 's,/[^/]\+$,,'`:$PATH"
make-install
make-policy

rm "$root/etc/dhclient.conf" # does not belong to this package

# Create the package meta information

mkdir -p "$root/var/lib/lrpkg"

conf="$root/var/lib/lrpkg/firewall.conf"
help="$root/var/lib/lrpkg/firewall.help"
list="$root/var/lib/lrpkg/firewall.list"
version="$root/var/lib/lrpkg/firewall.version"
md5sum="$root/var/lib/lrpkg/firewall.md5"

# Create firewall.conf

locate() { find $root -name "$1" | sed "s/$root//"; }

echo "$(locate firewall)	Firewall control script" > "$conf"
echo "$(locate firewall.policy)	Firewall policy" >> "$conf"
echo "$(locate fwup)	Start the firewall (Don't use this directly)" >> "$conf"
echo "$(locate fwdown)	Stop the firewall (Don't use this directly)" >> "$conf"
echo >> "$conf"

# Create firewall.help

firewall | sed 's/\.\/firewall/firewall/' > "$help"
echo >> "$help"

# Create firewall.version

echo "20041231-1" > "$version"
echo >> "$version"

# Create firewall.list

touch "$list"
touch "$md5sum"
find "$root" -type f -or -type l | sed "s/^$root//" >> "$list"
echo >> "$list"

# Create firewall.md5

md5sum `find "$root" -type f -a ! -name firewall.md5` | sed "s/ $root/\*/" >> "$md5sum"
echo >> "$md5sum"

# Create the LRP package

cd "$root"
tar czf ../firewall.lrp .
cd ..
rm -r "$root"

# Show the LRP package

ls -ls firewall.lrp
tar tzvf firewall.lrp

