#!/bin/sh
#
# firewall - http://fwup.org/
#
# Copyright (C) 1999-2001 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# or visit http://www.gnu.org/copyleft/gpl.html
#

# make-meta-uninstall - Uninstall the meta-firewall installation (without make)
#
# 20010507 raf <raf@raf.org>

rm -f /etc/rc.d/init.d/meta-firewall /etc/init.d/meta-firewall /etc/meta-firewall
rm -rf /etc/meta-firewall.d
