#!/bin/sh
#
# firewall - http://fwup.org/
#
# Copyright (C) 1999-2001 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# or visit http://www.gnu.org/copyleft/gpl.html
#

# make-install - Install the firewall scripts (without make)
#
# 20010507 raf <raf@raf.org>

START="rc2.d rc3.d rc4.d rc5.d"
STOP="rc0.d rc1.d rc6.d"
START_TIME="09"
STOP_TIME="91"

. ./firewall.policy
[ -d /usr/local/sbin ] || mkdir /usr/local/sbin || exit 1
install -m 744 fwup /usr/local/sbin || exit 1
install -m 744 fwdown /usr/local/sbin || exit 1
create() { if [ ! -f $1 ]; then echo '#!/bin/sh' > $1; echo >> $1; chmod u+x $1; fi; }
reload() { create $1; grep -q '/firewall reload' $1 || echo "[ -x $loc/firewall ] && $loc/firewall reload" >> $1; }
links() { for rc in $1; do [ -x $2/$rc/${3}firewall ] || ln -s ../init.d/firewall $2/$rc/${3}firewall; done; }
initd() { install -m 755 firewall $loc && links "$START" $1 S$START_TIME && links "$STOP" $1 K$STOP_TIME; }
dynamic() { if [ -z "$UNTRUSTED_ADDRESSES" ]; then ppp; dhcp; fi; }
rclocal() { install -m 755 firewall $loc && reload $1/rc.local; }
ppp() { [ -d /etc/ppp ] && reload /etc/ppp/ip-up.local && reload /etc/ppp/ip-down.local; }
dhcp() { if [ -d /etc/dhcpc ]; then for iface in $UNTRUSTED_INTERFACES; do reload /etc/dhcpc/dhcpcd-$iface.exe; done; fi; }
if [ -d /etc/rc.d/init.d ]; then loc=/etc/rc.d/init.d; initd /etc/rc.d; dynamic
elif [ -d /etc/init.d ]; then loc=/etc/init.d; initd /etc; dynamic
elif [ -x /etc/rc.d/rc.local ]; then loc=/etc; rclocal /etc/rc.d; dynamic
elif [ -x /etc/rc.local ]; then loc=/etc; rclocal /etc; dynamic
else exit 1
fi
