#!/usr/bin/perl -w
use strict;

# Prints a summary of connection tuples in a tcpdump output file

my %pairs = ();

main:
{
	while (<>)
	{
		my ($src, $dst, $rest) = $_ =~ /\S+ (\S+) > ([^:]+): (.*)$/;
		#die("Bad line: $_\n") unless defined $src and defined $dst;
		last unless defined $src and defined $dst;
		my ($srcport) = $src =~ /.*\.([^.]+)/;
		#die("Bad line: $_\n") unless defined $srcport;
		last unless defined $srcport;
		my ($dstport) = $dst =~ /.*\.([^.]+)/;
		#die("Bad line: $_\n") unless defined $dstport;
		last unless defined $dstport;
		my $conn = ($rest =~ /^S/ and $rest !~ / ack /) ? '-syn' : '';
		++$pairs{$src . ' -> ' . $dst . $conn};
	}

	for (sort keys %pairs)
	{
		print("$_ ($pairs{$_})\n");
	}

	exit(0);
}
