#!/usr/bin/perl -w
use strict;

#
# firewall: http://www.zip.com.au/~raf2/lib/software/firewall
#
# Copyright (C) 2000 raf <raf2@zip.com.au>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# or visit http://www.gnu.org/copyleft/gpl.html
#

# portsummary - Print a summary of connection tuples in a tcpdump output file
#
# 20000430 raf <raf2@zip.com.au>

my %pairs = ();

main:
{
	while (<>)
	{
		my ($src, $dst, $rest) = $_ =~ /\S+ (\S+) > ([^:]+): (.*)$/;
		#die("Bad line: $_\n") unless defined $src and defined $dst;
		last unless defined $src and defined $dst;
		my ($srcport) = $src =~ /.*\.([^.]+)/;
		#die("Bad line: $_\n") unless defined $srcport;
		last unless defined $srcport;
		my ($dstport) = $dst =~ /.*\.([^.]+)/;
		#die("Bad line: $_\n") unless defined $dstport;
		last unless defined $dstport;
		my $conn = ($rest =~ /^S/ and $rest !~ / ack /) ? '-syn' : '';
		++$pairs{$src . ' -> ' . $dst . $conn};
	}

	for (sort keys %pairs)
	{
		print("$_ ($pairs{$_})\n");
	}

	exit(0);
}
