#!/usr/bin/env perl
$^W = 1;
use strict;

# firewall - http://fwup.org/
#
# Copyright (C) 2000-2002 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# or visit http://www.gnu.org/copyleft/gpl.html

# tcpdump-histogram - prints a histogram of packets in tcpdump output
#
# 20000817 raf <raf@raf.org>

my %pairs;

while (<>)
{
	++$pairs{$1}, next
		if /^\S+ (arp who-has \S+ tell \S+)$/;

	++$pairs{$1}, next
		if /^\S+ (arp reply \S+ is-at \S+)$/;

	++$pairs{"icmp: $1 -> $2 $3"}, next
		if /^\S+ (\S+) > (\S+): icmp: (.*)$/;

	++$pairs{"udp: $1 -> $2"}, next
		if /^\S+ (\S+) > (\S+): udp /;

	++$pairs{"tcp: $1 -> $2"}, next
		if /^\S+ (\S+) > (\S+): .* ack /;

	++$pairs{"tcp: $1 -> $2 [Syn]"}, next
		if /^\S+ (\S+) > (\S+): S /;
}

for (sort keys %pairs)
{
	print("$_ ($pairs{$_} packet", (($pairs{$_} == 1) ? '' : 's'), ")\n");
}
