#!/usr/bin/perl -w
use strict;

# fwup - http://fwup.org/
#
# Copyright (C) 2000 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# or visit http://www.gnu.org/copyleft/gpl.html

# tuplegram - prints a histogram of connection tuples in tcpdump output
#
# 20000817 raf <raf@raf.org>

my %pairs = ();

main:
{
	while (<>)
	{
		my ($src, $dst, $rest) = $_ =~ /\S+ (\S+) > ([^:]+): (.*)$/;
		die("Bad line: $_\n") unless defined $src and defined $dst;
		last unless defined $src and defined $dst;
		++$pairs{'icmp: ' . $src . ' -> ' . $dst . ' ' . $1}, next
			if $rest =~ /^icmp: (.*)$/;
		my ($srcport) = $src =~ /\d+\.\d+\.\d+\.\d+\.([^.]+)/;
		my ($dstport) = $dst =~ /\d+\.\d+\.\d+\.\d+\.([^.]+)/;
		last unless defined $srcport and defined $dstport;
		++$pairs{'udp: ' . $src . ' -> ' . $dst}, next
			if $rest =~ /^udp/;
		my $conn = ($rest =~ /^S/ and $rest !~ / ack /) ? '-syn' : '';
		++$pairs{'tcp: ' . $src . ' -> ' . $dst . $conn};
	}

	for (sort keys %pairs)
	{
		print("$_ ($pairs{$_} packet", (($pairs{$_} == 1) ? '' : 's'), ")\n");
	}

	exit(0);
}
